[Setup]
AppId={{6C6F5E6E-2D6A-4C8E-9C7A-DELCARGOTRK01}
AppName=DelCargo Tracker
AppVersion=1.3
AppPublisher=DelCargo
AppPublisherURL=https://delcargo.example
DefaultDirName={localappdata}\DelCargo Tracker
DefaultGroupName=DelCargo Tracker
UninstallDisplayIcon={app}\DelCargo Tracker.exe
; Wizard/installer icon — generated by generate_icons.py from
; "Tracker Icon.png". IMPORTANT: run `python generate_icons.py` (which
; build_windows.bat now does automatically) before compiling this .iss —
; ISCC will fail to compile if icon.ico doesn't exist yet.
SetupIconFile=icon.ico
Compression=lzma2
SolidCompression=yes
OutputDir=dist
OutputBaseFilename=DelCargo_Tracker_Setup
PrivilegesRequired=lowest
DisableProgramGroupPage=yes
; Shown as a mandatory "I accept the agreement" step before Next is enabled —
; this is the installer-level license/consent acceptance step (screen
; monitoring consent + standard EULA terms).
LicenseFile=LICENSE.txt
WizardStyle=modern
SetupLogging=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "dist\DelCargo Tracker.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Start Menu entry — always created.
Name: "{group}\DelCargo Tracker"; Filename: "{app}\DelCargo Tracker.exe"
Name: "{group}\Uninstall DelCargo Tracker"; Filename: "{uninstallexe}"
; Desktop icon — opt-in via the "desktopicon" task below.
Name: "{userdesktop}\DelCargo Tracker"; Filename: "{app}\DelCargo Tracker.exe"; Tasks: desktopicon
; Pin to taskbar ("Start bar") — opt-in via the "taskbaricon" task below.
; Inno Setup has no direct "pin to taskbar" verb, so this creates a
; Quick Launch-style shortcut which Windows treats as pinnable; on modern
; Windows the user may need to right-click > "Pin to taskbar" once, since
; Microsoft removed silent taskbar-pinning for unsigned installers.
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\DelCargo Tracker"; Filename: "{app}\DelCargo Tracker.exe"; Tasks: taskbaricon
; Start-on-login shortcut — opt-in via the "startupicon" task below.
Name: "{userstartup}\DelCargo Tracker"; Filename: "{app}\DelCargo Tracker.exe"; Tasks: startupicon

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: unchecked
Name: "taskbaricon"; Description: "Pin DelCargo Tracker to the &taskbar"; GroupDescription: "Additional icons:"; Flags: unchecked
Name: "startupicon"; Description: "Start DelCargo Tracker automatically when I log in"; GroupDescription: "Startup:"; Flags: unchecked

[Run]
Filename: "{app}\DelCargo Tracker.exe"; Description: "Launch DelCargo Tracker"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Leaves the employee's saved setup code/config alone on uninstall by
; default (so a reinstall reconnects automatically) — nothing to add here
; unless a full wipe is wanted; documented for whoever revisits this.
